linters:
  eslint:
    # indicate where is the config file for stylelint
    config: './.eslintrc.json'

# add the files here you want to be ignored by stylelint
files:
  ignore:
      - 'bower_components/*'
      - 'node_modules/*'
      - 'dist/*'
      
      
      
 
